//
// City.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct City: Codable { 


    public var distance: Int
    public var title: String
    public var locationType: String
    public var woeid: Int
    public var lattLong: String

    public init(distance: Int, title: String, locationType: String, woeid: Int, lattLong: String) {
        self.distance = distance
        self.title = title
        self.locationType = locationType
        self.woeid = woeid
        self.lattLong = lattLong
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case distance
        case title
        case locationType = "location_type"
        case woeid
        case lattLong = "latt_long"
    }

}
