//
// Weather.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Weather: Codable { 


    public var id: Int
    public var weatherStateName: String
    public var weatherStateAbbr: String
    public var windDirectionCompass: String
    public var applicableDate: Date
    public var minTemp: Double
    public var maxTemp: Double
    public var theTemp: Double
    public var windSpeed: Double
    public var windDirection: Double
    public var airPressure: Double
    public var humidity: Int
    public var visibility: Double
    public var predictability: Int

    public init(id: Int, weatherStateName: String, weatherStateAbbr: String, windDirectionCompass: String, created: Date, applicableDate: Date, minTemp: Double, maxTemp: Double, theTemp: Double, windSpeed: Double, windDirection: Double, airPressure: Double, humidity: Int, visibility: Double, predictability: Int) {
        self.id = id
        self.weatherStateName = weatherStateName
        self.weatherStateAbbr = weatherStateAbbr
        self.windDirectionCompass = windDirectionCompass
        self.applicableDate = applicableDate
        self.minTemp = minTemp
        self.maxTemp = maxTemp
        self.theTemp = theTemp
        self.windSpeed = windSpeed
        self.windDirection = windDirection
        self.airPressure = airPressure
        self.humidity = humidity
        self.visibility = visibility
        self.predictability = predictability
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case weatherStateName = "weather_state_name"
        case weatherStateAbbr = "weather_state_abbr"
        case windDirectionCompass = "wind_direction_compass"
        case applicableDate = "applicable_date"
        case minTemp = "min_temp"
        case maxTemp = "max_temp"
        case theTemp = "the_temp"
        case windSpeed = "wind_speed"
        case windDirection = "wind_direction"
        case airPressure = "air_pressure"
        case humidity
        case visibility
        case predictability
    }

}
